### ISSUE TITLE
Feedback on existing content

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/advanced-viz-cookbook#12]
Requesting feedback from @kafitzgerald

**Comment by kafitzgerald** [comment]
Still need to get through good-viz and onward, but here's some initial feedback.

Overall, it looks like you've got a great start!  

I like the overview / comparison notebook quite a lot.   

Some higher level thoughts:
* This seems like a lot to bite off: https://projectpythia.org/advanced-viz-cookbook/README.html#structure.  In particular, the Basics of Geoscience Visualization sounds like it could be a textbook on its own.  I wonder if there's a good way to scale back the scope a little?  Maybe that'll be more clear though after this comes together.    

Minor suggestions:
* Might be good to link to the docs or some other reference page for the various packages mentioned here: https://projectpythia.org/advanced-viz-cookbook/README.html#motivation
* Maybe change "image" to "outcome" or similar here: https://github.com/ProjectPythia/advanced-viz-cookbook/blob/7666fd76fe31a77339c293cbbd08d10e1ecb1d48/README.md?plain=1#L15
* Maybe leave out the "on the cloud" bit here (lots of ways to make this work): https://projectpythia.org/advanced-viz-cookbook/README.html#interactive-visualization
* "3-dimensional" to "multidimensional" here: https://projectpythia.org/advanced-viz-cookbook/README.html#d-visualization
* What do you mean by animated vs e.g. interactive?
* For the Seaborn description in the comparison notebook I would say something along the lines of it being "a high level interface for creating statistical visualizations built on matplotlib"
* Does the GPU-enabled environment requirement bit belong somewhere else?  I'm fairly confident seaborn doesn't need that.
* good-viz link from comparison notebook is broken

Typos:
* "to you**r** Python visualization toolbox" in this line: https://github.com/ProjectPythia/advanced-viz-cookbook/blob/7666fd76fe31a77339c293cbbd08d10e1ecb1d48/README.md?plain=1#L13
* "plottig" to "plotting" in the matplotlib section of the comparison notebook
* the "Let us know!" link is broken in this notebook: https://github.com/ProjectPythia/advanced-viz-cookbook/blob/main/notebooks/comparison.ipynb
* GeoCat-examples to GeoCAT-examples in here: https://github.com/ProjectPythia/advanced-viz-cookbook/blob/main/notebooks/comparison.ipynb
* Matploblib to Matplotlib in: https://github.com/ProjectPythia/advanced-viz-cookbook/blob/main/notebooks/comparison.ipynb
* Vapor to VAPOR 
* "Plotly is another choice for **interacting plotting**" to "interactive plotting"
* "statistical graphhics" to statistical graphics" in the seaborn description
